package k9crypt

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha512"
	"crypto/subtle"
	"encoding/binary"
	"errors"
	"io"
	"sync"

	"github.com/K9Crypt/k9crypt-go/src/compression"
	"github.com/K9Crypt/k9crypt-go/src/constants"
	"github.com/K9Crypt/k9crypt-go/src/encryption"

	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/pbkdf2"
)

type K9Crypt struct {
	secretKey               []byte
	aesEncryptor            *encryption.AesEncryptor
	sha512Hasher            *encryption.Sha512Hasher
	argon2Hasher            *encryption.Argon2Hasher
	zlibCompressor          *compression.ZlibCompressor
	lzmaCompressor          *compression.LzmaCompressor
	compressionType         constants.CompressionType
	defaultCompressionLevel int
	autoGenerated           bool
	mu                      sync.RWMutex
}

type Options struct {
	CompressionLevel int
}

type EncryptOptions struct {
	CompressionLevel *int
	TimeStepSeconds  uint32
	IssuedAtUnix     *int64
}

type DecryptOptions struct {
	MaxAgeSeconds           *int64
	AllowedClockSkewSeconds int64
	NowUnixSeconds          *int64
	AllowLegacyPayloads     *bool
}

func New(secretKey string) (*K9Crypt, error) {
	if secretKey == "" {
		return nil, errors.New("secret key must not be empty")
	}

	keyBytes := []byte(secretKey)
	encryptor := newK9Crypt(keyBytes, false)
	zeroBytes(keyBytes)

	return encryptor, nil
}

func NewGenerated() (*K9Crypt, error) {
	keyBytes, err := secureRandomBytes(constants.GeneratedKeySize)
	if err != nil {
		return nil, errors.New("key generation failed")
	}

	encryptor := newK9Crypt(keyBytes, true)
	zeroBytes(keyBytes)

	return encryptor, nil
}

func NewWithKey(secretKey []byte) (*K9Crypt, error) {
	if secretKey == nil {
		return NewGenerated()
	}

	if len(secretKey) == 0 {
		return nil, errors.New("secret key must not be empty")
	}

	keyBytes := make([]byte, len(secretKey))
	copy(keyBytes, secretKey)

	encryptor := newK9Crypt(keyBytes, false)
	zeroBytes(keyBytes)

	return encryptor, nil
}

func NewWithOptions(secretKey string, compressionLevel int) (*K9Crypt, error) {
	k, err := New(secretKey)
	if err != nil {
		return nil, err
	}

	err = k.SetCompressionLevel(compressionLevel)
	if err != nil {
		return nil, err
	}

	return k, nil
}

func NewWithKeyAndOptions(secretKey []byte, compressionLevel int) (*K9Crypt, error) {
	k, err := NewWithKey(secretKey)
	if err != nil {
		return nil, err
	}

	err = k.SetCompressionLevel(compressionLevel)
	if err != nil {
		return nil, err
	}

	return k, nil
}

func NewGeneratedWithOptions(compressionLevel int) (*K9Crypt, error) {
	k, err := NewGenerated()
	if err != nil {
		return nil, err
	}

	err = k.SetCompressionLevel(compressionLevel)
	if err != nil {
		return nil, err
	}

	return k, nil
}

func newK9Crypt(keyBytes []byte, autoGenerated bool) *K9Crypt {
	secretKey := make([]byte, len(keyBytes))
	copy(secretKey, keyBytes)

	return &K9Crypt{
		secretKey:               secretKey,
		aesEncryptor:            encryption.NewAesEncryptor(),
		sha512Hasher:            encryption.NewSha512Hasher(),
		argon2Hasher:            encryption.NewArgon2Hasher(),
		zlibCompressor:          compression.NewZlibCompressor(),
		lzmaCompressor:          compression.NewLzmaCompressor(),
		compressionType:         constants.CompressionZlib,
		defaultCompressionLevel: constants.CompressionLevel,
		autoGenerated:           autoGenerated,
	}
}

func (k *K9Crypt) GetGenerated() []byte {
	k.mu.RLock()
	defer k.mu.RUnlock()

	if !k.autoGenerated {
		return nil
	}

	keyBytes := make([]byte, len(k.secretKey))
	copy(keyBytes, k.secretKey)
	return keyBytes
}

func (k *K9Crypt) SetCompressionLevel(level int) error {
	if level < 0 || level > 9 {
		return errors.New("compression level must be between 0 and 9")
	}

	k.mu.Lock()
	defer k.mu.Unlock()

	k.defaultCompressionLevel = level
	return k.zlibCompressor.SetLevel(level)
}

func (k *K9Crypt) GetCompressionLevel() int {
	k.mu.RLock()
	defer k.mu.RUnlock()

	return k.defaultCompressionLevel
}

func (k *K9Crypt) Encrypt(plaintext string) (string, error) {
	return k.EncryptWithOptions(plaintext, nil)
}

func (k *K9Crypt) EncryptWithOptions(plaintext string, options *EncryptOptions) (string, error) {
	return k.encryptBytes([]byte(plaintext), false, options)
}

func (k *K9Crypt) EncryptBytes(plaintext []byte, options *EncryptOptions) (string, error) {
	input := plaintext
	if input == nil {
		input = []byte{}
	}

	return k.encryptBytes(input, true, options)
}

func (k *K9Crypt) Decrypt(encryptedData string) (string, error) {
	return k.DecryptWithOptions(encryptedData, nil)
}

func (k *K9Crypt) DecryptWithOptions(encryptedData string, options *DecryptOptions) (string, error) {
	plaintext, err := k.DecryptBytes(encryptedData, options)
	if err != nil {
		return "", err
	}

	return string(plaintext), nil
}

func (k *K9Crypt) DecryptBytes(encryptedData string, options *DecryptOptions) ([]byte, error) {
	decodedData, err := decodePayloadString(encryptedData)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	return k.decryptDecodedBytes(decodedData, options)
}

func (k *K9Crypt) encryptBytes(plaintext []byte, isBinary bool, options *EncryptOptions) (string, error) {
	if len(plaintext) > constants.MaxPlaintextSize {
		return "", errors.New("encryption failed")
	}

	compressionLevel, err := k.resolveCompressionLevel(options)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	input := make([]byte, len(plaintext))
	copy(input, plaintext)
	isCompressed := compressionLevel > 0
	if isCompressed {
		input, err = compressDataWithLevel(input, compressionLevel)
		if err != nil {
			return "", errors.New("encryption failed")
		}
	}

	header, metadata, err := createTimeHeader(options, isBinary, isCompressed)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	salt, err := secureRandomBytes(constants.SaltSize)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	key, err := k.derivePayloadKey(salt, metadata)
	if err != nil {
		return "", errors.New("encryption failed")
	}
	defer zeroBytes(key)

	encryptedData, err := k.aesEncryptor.EncryptVersioned(input, key, header)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	body, err := createPayloadBody(header, salt, encryptedData.Ivs, encryptedData.Encrypted, encryptedData.Tag)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	integritySalt, err := secureRandomBytes(constants.Argon2SaltSize)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	dataHash, err := macHash(body, integritySalt, key)
	if err != nil {
		return "", errors.New("encryption failed")
	}
	defer zeroBytes(dataHash)

	payload, err := buildPayload(body, integritySalt, dataHash)
	if err != nil {
		return "", errors.New("encryption failed")
	}

	return payload, nil
}

func (k *K9Crypt) decryptDecodedBytes(decodedData []byte, options *DecryptOptions) ([]byte, error) {
	if len(decodedData) > constants.MaxCiphertextSize {
		return nil, errors.New("decryption failed")
	}

	if hasVersionedPayload(decodedData) {
		return k.decryptVersionedPayload(decodedData, options)
	}

	if !legacyPayloadsAllowed(options) {
		return nil, errors.New("decryption failed")
	}

	return k.decryptLegacyPayload(decodedData)
}

func (k *K9Crypt) decryptVersionedPayload(decodedData []byte, options *DecryptOptions) ([]byte, error) {
	payload, err := parseVersionedPayload(decodedData)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	if payload.version < constants.PayloadCurrentVersion && !legacyPayloadsAllowed(options) {
		return nil, errors.New("decryption failed")
	}

	if payload.version < constants.PayloadVersionV4 {
		if !verifyVersionedHash(payload.body, payload.dataHash, payload.integritySalt, k.resolveHashAuthKey(payload)) {
			return nil, errors.New("decryption failed")
		}
	}

	key, err := k.derivePayloadKey(payload.salt, payload.timeMetadata)
	if err != nil {
		return nil, errors.New("decryption failed")
	}
	defer zeroBytes(key)

	if payload.version >= constants.PayloadVersionV4 {
		if !verifyMacHash(payload.body, payload.dataHash, payload.integritySalt, key) {
			return nil, errors.New("decryption failed")
		}
	}

	err = validateFreshness(payload, options)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	decryptedData, err := k.aesEncryptor.DecryptVersioned(payload.encrypted, key, payload.ivs, payload.tag, payload.header)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	plaintext := decryptedData
	if payload.timeMetadata != nil && payload.timeMetadata.isCompressed {
		plaintext, err = decompressVersionedData(decryptedData)
		if err != nil {
			return nil, errors.New("decryption failed")
		}
	}

	if len(plaintext) > constants.MaxPlaintextSize {
		return nil, errors.New("decryption failed")
	}

	result := make([]byte, len(plaintext))
	copy(result, plaintext)
	return result, nil
}

func (k *K9Crypt) decryptLegacyPayload(decodedData []byte) ([]byte, error) {
	if len(decodedData) < constants.LegacyMinPayloadSize {
		return nil, errors.New("decryption failed")
	}

	reader := bytes.NewReader(decodedData)
	paddingSizeByte, err := reader.ReadByte()
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	paddingSize := int(paddingSizeByte)
	if paddingSize < 4 || paddingSize > 16 || reader.Len() < paddingSize+4 {
		return nil, errors.New("decryption failed")
	}

	_, err = reader.Seek(int64(paddingSize), io.SeekCurrent)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	saltLen, err := readUint32Little(reader)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	if saltLen != constants.Argon2SaltSize || reader.Len() < int(saltLen)+4 {
		return nil, errors.New("decryption failed")
	}

	salt := make([]byte, saltLen)
	_, err = io.ReadFull(reader, salt)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	hashLen, err := readUint32Little(reader)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	if hashLen != sha512.Size || reader.Len() < int(hashLen)+1 {
		return nil, errors.New("decryption failed")
	}

	hash := make([]byte, hashLen)
	_, err = io.ReadFull(reader, hash)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	remaining := make([]byte, reader.Len())
	_, err = io.ReadFull(reader, remaining)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	keys, err := k.deriveKeys(k.secretKey, salt)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	decryptedData, err := k.aesEncryptor.MultiLayerDecrypt(remaining, keys)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	decompressedData, err := k.decompressData(decryptedData)
	if err != nil {
		return nil, errors.New("decryption failed")
	}

	if len(decompressedData) > constants.MaxPlaintextSize {
		return nil, errors.New("decryption failed")
	}

	if !k.verifyHash(decompressedData, salt, hash) {
		return nil, errors.New("decryption failed")
	}

	return decompressedData, nil
}

func (k *K9Crypt) resolveCompressionLevel(options *EncryptOptions) (int, error) {
	level := k.GetCompressionLevel()
	if options != nil && options.CompressionLevel != nil {
		level = *options.CompressionLevel
	}

	if level < 0 || level > 9 {
		return 0, errors.New("invalid compression level")
	}

	return level, nil
}

func (k *K9Crypt) derivePayloadKey(salt []byte, metadata *timeMetadata) ([]byte, error) {
	if len(k.secretKey) == 0 || len(salt) != constants.SaltSize {
		return nil, errors.New("key derivation failed")
	}

	pepperedPassword := make([]byte, len(k.secretKey)+len(constants.PayloadPepper))
	copy(pepperedPassword, k.secretKey)
	copy(pepperedPassword[len(k.secretKey):], constants.PayloadPepper)
	baseKey := pbkdf2.Key(pepperedPassword, salt, constants.Pbkdf2Iterations, constants.KeySize, sha512.New)
	zeroBytes(pepperedPassword)

	if metadata == nil {
		return baseKey, nil
	}

	finalKey, err := deriveTimeScopedKey(baseKey, metadata)
	zeroBytes(baseKey)
	if err != nil {
		return nil, errors.New("key derivation failed")
	}

	return finalKey, nil
}

func deriveTimeScopedKey(baseKey []byte, metadata *timeMetadata) ([]byte, error) {
	if len(baseKey) != constants.KeySize || metadata == nil || metadata.stepSeconds == 0 || metadata.issuedAt < 0 {
		return nil, errors.New("key derivation failed")
	}

	bucket := uint64(metadata.issuedAt / int64(metadata.stepSeconds))
	context := make([]byte, len(constants.TimeKeyContext)+12)
	copy(context, constants.TimeKeyContext)
	binary.BigEndian.PutUint32(context[len(constants.TimeKeyContext):], metadata.stepSeconds)
	binary.BigEndian.PutUint64(context[len(constants.TimeKeyContext)+4:], bucket)

	h := hmac.New(sha512.New, baseKey)
	_, err := h.Write(context)
	if err != nil {
		zeroBytes(context)
		return nil, errors.New("key derivation failed")
	}

	digest := h.Sum(nil)
	finalKey := make([]byte, constants.KeySize)
	copy(finalKey, digest[:constants.KeySize])
	zeroBytes(context)
	zeroBytes(digest)

	return finalKey, nil
}

func (k *K9Crypt) deriveKeys(password []byte, salt []byte) ([][]byte, error) {
	masterKey, err := k.argon2Hasher.Hash(password, salt)
	if err != nil {
		return nil, errors.New("key derivation failed")
	}
	defer zeroBytes(masterKey)

	hashedMasterKey, err := k.sha512Hasher.HashWithSalt(masterKey, salt)
	if err != nil {
		return nil, errors.New("key derivation failed")
	}
	defer zeroBytes(hashedMasterKey)

	keys := make([][]byte, 5)
	keyChan := make(chan struct {
		index int
		key   []byte
		err   error
	}, 5)

	for i := 0; i < 5; i++ {
		go func(idx int) {
			keyMaterial := make([]byte, len(hashedMasterKey)+1)
			copy(keyMaterial, hashedMasterKey)
			keyMaterial[len(hashedMasterKey)] = byte(idx)
			keyHash, hashErr := k.sha512Hasher.Hash(keyMaterial)
			zeroBytes(keyMaterial)
			if hashErr != nil {
				keyChan <- struct {
					index int
					key   []byte
					err   error
				}{idx, nil, hashErr}
				return
			}
			key := make([]byte, constants.KeySize)
			copy(key, keyHash[:constants.KeySize])
			zeroBytes(keyHash)
			keyChan <- struct {
				index int
				key   []byte
				err   error
			}{idx, key, nil}
		}(i)
	}

	var firstErr error
	for i := 0; i < 5; i++ {
		result := <-keyChan
		if result.err != nil {
			firstErr = result.err
			continue
		}
		keys[result.index] = result.key
	}

	if firstErr != nil {
		return nil, errors.New("key derivation failed")
	}

	return keys, nil
}

func (k *K9Crypt) resolveHashAuthKey(payload *versionedPayload) []byte {
	if payload != nil && payload.version == constants.PayloadVersionV3 {
		return k.secretKey
	}

	return nil
}

func macHash(data []byte, salt []byte, key []byte) ([]byte, error) {
	if len(salt) != constants.Argon2SaltSize || len(key) != constants.KeySize {
		return nil, errors.New("hashing failed")
	}

	h := hmac.New(sha512.New, key)
	_, err := h.Write(salt)
	if err != nil {
		return nil, errors.New("hashing failed")
	}

	_, err = h.Write(data)
	if err != nil {
		return nil, errors.New("hashing failed")
	}

	return h.Sum(nil), nil
}

func verifyMacHash(data []byte, expectedHash []byte, salt []byte, key []byte) bool {
	if len(expectedHash) != constants.Argon2HashLength {
		return false
	}

	computedHash, err := macHash(data, salt, key)
	if err != nil {
		return false
	}
	defer zeroBytes(computedHash)

	return hmac.Equal(computedHash, expectedHash)
}

func verifyVersionedHash(data []byte, expectedHash []byte, salt []byte, authKey []byte) bool {
	if len(expectedHash) != constants.Argon2HashLength || len(salt) != constants.Argon2SaltSize {
		return false
	}

	digest := computeVersionedHmac(data, authKey)
	defer zeroBytes(digest)
	computedHash := argon2.IDKey(digest, salt, constants.Argon2Time, constants.Argon2Memory, constants.Argon2Threads, constants.Argon2HashLength)
	defer zeroBytes(computedHash)

	if len(computedHash) != len(expectedHash) {
		return false
	}

	return subtle.ConstantTimeCompare(computedHash, expectedHash) == 1
}

func computeVersionedHmac(data []byte, authKey []byte) []byte {
	hmacKey := constants.PayloadHmacKey
	var derivedHmacKey []byte

	if len(authKey) > 0 {
		deriver := hmac.New(sha512.New, constants.PayloadHmacKey)
		deriver.Write(authKey)
		derivedHmacKey = deriver.Sum(nil)
		hmacKey = derivedHmacKey
	}

	if derivedHmacKey != nil {
		defer zeroBytes(derivedHmacKey)
	}

	h := hmac.New(sha512.New, hmacKey)
	h.Write(data)
	return h.Sum(nil)
}

func (k *K9Crypt) generateHash(data []byte, salt []byte) ([]byte, error) {
	return k.sha512Hasher.HmacHashWithSalt(data, salt)
}

func (k *K9Crypt) verifyHash(data []byte, salt []byte, expectedHash []byte) bool {
	return k.sha512Hasher.HmacVerifyWithSalt(data, salt, expectedHash)
}

func compressDataWithLevel(data []byte, level int) ([]byte, error) {
	compressor := compression.NewZlibCompressor()
	err := compressor.SetLevel(level)
	if err != nil {
		return nil, errors.New("compression error")
	}

	return compressor.Compress(data)
}

func decompressVersionedData(data []byte) ([]byte, error) {
	compressor := compression.NewZlibCompressor()
	return compressor.DecompressWithLimit(data, constants.MaxPlaintextSize)
}

func (k *K9Crypt) compressData(data []byte) ([]byte, error) {
	compressionType := k.compressionType
	if compressionType == constants.CompressionZlib {
		compressor := compression.NewZlibCompressor()
		compressor.SetLevel(k.GetCompressionLevel())
		return compressor.Compress(data)
	}

	if compressionType == constants.CompressionLzma {
		return compression.NewLzmaCompressor().Compress(data)
	}

	return nil, errors.New("compression error")
}

func (k *K9Crypt) decompressData(data []byte) ([]byte, error) {
	compressionType := k.compressionType
	if compressionType == constants.CompressionZlib {
		return compression.NewZlibCompressor().Decompress(data)
	}

	if compressionType == constants.CompressionLzma {
		return compression.NewLzmaCompressor().Decompress(data)
	}

	return nil, errors.New("decompression error")
}

func secureRandomBytes(size int) ([]byte, error) {
	if size <= 0 {
		return nil, errors.New("invalid random size")
	}

	data := make([]byte, size)
	_, err := io.ReadFull(rand.Reader, data)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func readUint32Little(reader *bytes.Reader) (uint32, error) {
	data := make([]byte, 4)
	_, err := io.ReadFull(reader, data)
	if err != nil {
		return 0, err
	}

	return binary.LittleEndian.Uint32(data), nil
}

func zeroBytes(data []byte) {
	for i := range data {
		data[i] = 0
	}
}
